### ISSUE TITLE
Silverpeas Configuration

### ISSUE THREAD

**Issue by gueeme** [Silverpeas/Silverpeas-Components#578]
I'm sorry if it's not the right place to ask that but I did not find any supporting material on the internet.
I would like to know if there is any material (if possible in English) on how to set up Silverpeas as an intranet. 
And also how can I translate it into Brazilian Portuguese.

Thanks

**Comment by NicolasEYSSERIC** [comment]
Hi,

You will find all needed information to install Silverpeas on this page (in English) : https://www.silverpeas.org/installation/installationV6.html

If you require any support : https://www.silverpeas.org/support.html

Regards,
Nicolas

**Comment by mmoqui** [comment]
Hi gueeme,
For the translations, all the of them are located in the _PROJECT_NAME-configuration_ subproject. For example, for the *Kmelia* project in *Silverpeas-Components*, in *kmelia/kmelia-configuration* subproject . For the *Silverpeas-Core* project, in the *core-configuration* subproject. 

In each of the subproject, the resource bundles are located in *src/main/config/properties/org/silverpeas/COMPONENT_NAME/multilang/*. For example, for the *Kmelia* project in *Silverpeas-Components*: *src/main/properties/silverpeas/kmelia/multilang/*
